name: Rainbow
main: com.whede1601.Rainbow.Rainbow
version: 4.3
author: whede1601
commands:
  jemote:
  name:
  e:
  kit:
  ride:
  throw:
  diw:
  cron:
  jot:
  NameColor:
  color:
  ragequit:
  calmquit:
  kinder:
  ride: